name: RankUp
main: rankup\RankUp
version: 0.1
author: Falk
api: [1.4.0]
load: POSTWORLD
softdepend: ["EconomyAPI", "PocketMoney", "XPermissions"]
permissions:
 rankup:
  default: true
  children:
    rankup.rankup:
      default: true
      description: Allow ranking up
    rankup.groups:
      default: false
      description: Do NOT set this. It is used for group managment.