#   _______                       __        __    __
#  /       \                     /  |      /  |  /  |
#  $$$$$$$  |  ______   _______  $$ |   __ $$ |  $$ |  ______
#  $$ |__$$ | /      \ /       \ $$ |  /  |$$ |  $$ | /      \
#  $$    $$<  $$$$$$  |$$$$$$$  |$$ |_/$$/ $$ |  $$ |/$$$$$$  |
#  $$$$$$$  | /    $$ |$$ |  $$ |$$   $$<  $$ |  $$ |$$ |  $$ |
#  $$ |  $$ |/$$$$$$$ |$$ |  $$ |$$$$$$  \ $$ \__$$ |$$ |__$$ |
#  $$ |  $$ |$$    $$ |$$ |  $$ |$$ | $$  |$$    $$/ $$    $$/
#  $$/   $$/  $$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/  $$$$$$$/
#                                                    $$ |
#                                                    $$ |
#                                                    $$/
# The easy prison rankup plugin for PocketMine-MP
unleash-the-rankupdoesgroups: true
  # If you set this to false RankUpDoesGroups won't be loaded.
  # This means that you can't set it as your groupmanager.
  # It is highly recommended not to change this.
preferred-economy: "rankup\\economy\\Economy"
  # Set your preferred economy
  # rankup\\economy\\Economy and rankup\\economy\\PocketMoney are available by default
  # Set to false for autoloading (only offcially supported economys will autoload).
preferred-groupmanager: "rankup\\permission\\RankUpDoesGroups"
  # Set your preferred group manager
  # rankup\\permission\\RankUpDoesGroups and rankup\\permission\\xPermissions are available.
  # RankUpDoesGroups is a super barebones alternative for users who don't use xPerms

ranks: # Define your ranks here
  A: 10
  B: 15
  C: 30
  D: 50
